// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbjlpvtvwykfjvijxyio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiamxwdnR2d3lrZmp2aWp4eWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTg0MjUsImV4cCI6MjA2NzM5NDQyNX0.5U4MJzas-GO3fd2QhLuIgSAHxS5-R4Ivcxm_HNj3imc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});